### ISSUE TITLE
Weld Script welding hinges parts and breaking train boogies

### ISSUE THREAD

**Issue by Osifilms22** [jake-baxter/rblx-train-driving-system#30]
Hello,
I've recently started using this system with a train model and it works perfectly with only 1 coach. However, when I coupled other coaches they would just derrail when entering a curve. To solve this, I created a working boogie with hinges to make the gliders steer when entering the curve. But with the weld script the boogies get welded and the hinge cannot rotate and makes the steering impossible. I already enabled the NEVER_BREAK_JOINTS which suposedly would fix the problem. Any help?
![image](https://user-images.githubusercontent.com/120324864/206913749-f6dfd66e-5fd4-4cd5-8dfe-2872e7639fb1.png)
![image](https://user-images.githubusercontent.com/120324864/206913787-7fdeb3fe-7376-4494-b968-f45cddf9fac0.png)

**Comment by jake-baxter** [comment]
Not to do with this driving system
